[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "yfinance>=0.2.65",,
  "openai>=1.40.0",
  "pydantic>=2.7.0"
]
